UDP:
	gcc 1st/serverUDP.c -o serverUDP_1
	gcc clientUDP.c -o clientUDP
TCP:
	gcc 1st/serverTCP.c -o serverTCP_1
	gcc 2nd/serverTCP.c -pthread -o serverTCP_2
	gcc 3rd/serverTCP.c -pthread -o serverTCP_3
	gcc clientTCP.c -o clientTCP
